---
- hosts: localhost
  become: false
  tasks:

    - name: Create new  Routers
      azure_rm_virtualmachine_info:
        resource_group: AnsibleTower-Killian-Zoubayer
        name: Router-1
      register: result
      until: result.stdout.find("Error") != -1
      delay: 10
