---
- hosts: localhost
  become: false
  tasks:
    - name: deploy Routers
      azure_rm_virtualmachine:
        resource_group: AnsibleTower-Killian-Zoubayer
        name: zrouter1
        admin_username: "{{ ansible_username }}"
        admin_password: "{{ ansible_password }}"
        image:
          offer: cisco-csr-1000v
          publisher: cisco
          sku: '16_12-payg-sec'
          version: 16.12.120190816
        data_disks:
          - lun: 0
            disk_size_gb: 8
        location: francecentral
        vm_size: Standard_DS4_v2
        subnet: zrouter1-subnet
        virtual_network_name: ansible-vnet

