---
- hosts: localhost
  become: yes
  tasks:
    - name: deploy Routers
      azure_rm_virtualmachine:
        resource_group: AnsibleTower-Killian-Zoubayer
        name: "{{ item }}"
        admin_username: "{{ ansible_ssh_user }}"
        admin_password: "{{ ansible_ssh_password }}"
        image:
          offer: cisco-csr-1000v
          publisher: cisco
          sku: '16_12-payg-sec'
          version: 16.12.120190816
        data_disks:
          disk_size_gb: 8
          lun: 0
        location: francecentral
        vm_size: Standard_DS4_v2
        subnet: "{{ item }}-subnet"
        virtual_network_name: ansible-vnet
      with_items:
        - Routz1
        - Routz2

