---
- hosts: localhost
  become: false
  tasks:

    - name: Create new  Routers
      azure_rm_virtualmachine:
        resource_group: AnsibleTower-Killian-Zoubayer
        name: zrouter2
        admin_username: "{{ ansible_username }}"
        admin_password: "{{ ansible_password }}"
        plan:
          product: cisco-csr-1000v
          publisher: cisco
          name: '16_12-payg-sec'
        data_disks:
          - lun: 0
            disk_size_gb: 8
        location: francecentral
        vm_size: Standard_DS4_v2
        subnet: Router-1-Subnet
        virtual_network_name: ansible-vnet

