---
- hosts: localhost
  become: false
  tasks:

    - name: Create new  Routers
      azure_rm_virtualmachine:
        resource_group: AnsibleTower-Killian-Zoubayer
        name: "{{ item.name }}"
        admin_username: "{{ ansible_username }}"
        admin_password: "{{ ansible_password }}"
        image:
          offer: cisco-csr-1000v
          publisher: cisco
          sku: '16_12-payg-sec'
          version: 16.12.120190816
        plan:
          product: cisco-csr-1000v
          publisher: cisco
          name: '16_12-payg-sec'
        data_disks:
          - lun: 0
            disk_size_gb: 8
        os_disk_size_gb: 8
        location: francecentral
        vm_size: Standard_DS4_v2
        subnet: "{{ item.name }}-Subnet"
        virtual_network_name: ansible-vnet
        network_interfaces: "{{ item.interface }}"
        tags:
          env: demo
      with_items:
        - { name: Router-1 , interface: "Router-1VMNic,f1_1" } 
        - { name: Router-2 , interface: "Router-2VMNic,f2_1,f2_2"}


    - name: To Wait till the routers are Created
      wait_for:
        host: "{{ item }}"
        state: present
        delay: 40
      with_items:
        - Router-1
        - Router-2
