---
- hosts: localhost
  become: false
  tasks:

    - name: Delete the Routers and the associated storage
      azure_rm_virtualmachine:
        resource_group: AnsibleTower-Killian-Zoubayer
        name: "{{ item }}"
        state: absent
        remove_on_absent: 
          - virtual_storage
          - public_ips
      with_items:
        - Router-4
        - zrouter3
        - zrouter4
        - zrouter5
      async: 45
      poll: 0

    - name: To Wait till the routers are Deleted
      wait_for:
        host: "{{ item }}"
        state: absent
        delay: 40
      with_items:
        - Router-4
        - zrouter3
        - zrouter4
        - zrouter5

    
    - debug:
        msg: "All Resources are deleted"
      
      