---
- hosts: localhost
  become: false
  tasks:

    - name: Create new  Routers
      azure_rm_virtualmachine:
        resource_group: AnsibleTower-Killian-Zoubayer
        name: "{{ item }}"
        state: absent
        remove_on_absent: 
          - virtual_storage
          - public_ips
      with_items:
        - Router-2
        - Router-3
        - Router-4
        - zrouter3
        - zrouter4
        - zrouter5
      async: 45
      poll: 0

    - name: Create new  Routers
      azure_rm_virtualmachine_info:
        resource_group: AnsibleTower-Killian-Zoubayer
        name: Router-1
      register: result
      until: result.stdout.find("Error") != -1
      delay: 10

    - debug:
      msg: "All Resources are deleted"
      
      