---
- hosts: localhost
  become: false
  tasks:

    - name: Delete the Routers and the associated storage
      azure_rm_virtualmachine:
        resource_group: AnsibleTower-Killian-Zoubayer
        name: "{{ item }}"
        state: absent
        remove_on_absent: 
          - virtual_storage
          - public_ips
      with_items:
        - Router-1
        - Router-2
        - Router-3
        - Router-4

      async: 45
      poll: 0

    - name: To Wait till the routers are Deleted
      wait_for:
        host: "{{ item }}"
        state: absent
      with_items:
        - Router-1
        - Router-2
        - Router-3
        - Router-4

    
    - debug:
        msg: "All Resources are deleted"
      
      