---
- name: GENERATE OS REPORT FROM ROUTERS
  hosts: env
  connection: network_cli
  gather_facts: no

  tasks:
    - name: GATHER ROUTER FACTS
      ios_facts:

    - name: RENDER FACTS AS A REPORT
      template:
        src: /routerinfo/template/os_report.j2
        dest: reports/{{ inventory_hostname }}.md

    - name: CONSOLIDATE THE IOS DATA
      assemble:
        src: reports/
        dest: network_os_report.md
      delegate_to: localhost
      run_once: yes
