---
- name: PING ALL THE ROUTER NETWORK
  hosts: localhost  # Executes the playbook across the all the hosts under the SmartInventory
  connection: network_cli # Informs to use the network connections for the router
  gather_facts: false 

  tasks:
    - name: PING TEST TO PRIVATE IP
      command: ping "{{ item }}"
      with_items:
        - 10.0.20.4
        - 10.0.30.4