---
- name: PING ALL THE ROUTER NETWORK
  hosts: env  # Executes the playbook across the all the hosts under the SmartInventory
  connection: network_cli # Informs to use the network connections for the router
  gather_facts: false 

  tasks:

    - debug:
        msg: "{{ ansible_facts['private_ip'] }}"
#
#    - name: Run ping to rtr4
#      register: ping_result
#      ios_ping:
#        dest: "{{ ansible_facts['private_ip'] }}"
#        state: present