---
- name: PING ALL THE ROUTER NETWORK
  hosts: all  # Executes the playbook across the all the hosts under the SmartInventory
  connection: network_cli # Informs to use the network connections for the router
  gather_facts: false 

  tasks:

    - name: Run ping to rtr4
      register: ping_result
      net_ping:
        dest: "{{ ansible_hostname }}"
        state: present