---
- hosts: localhost
  gather_facts: no
  vars:
    machine:
      username: '{{ ansible_user }}'
      password: '{{ ansible_password }}'

  tasks:
  
    - name: to Display
      debug:
        var: machine
