---
- name: GATHER INFORMATION FROM ROUTERS
  hosts: env
  connection: network_cli
  gather_facts: no

  tasks:
    - name: GATHER ROUTER FACTS
      ios_facts:
      register: show_output

    - debug:
        var: {{ show_output }}