---
- name: GATHER INFORMATION FROM ROUTERS
  hosts: env
  connection: network_cli
  gather_facts: no
  environment:
    ansible_network_os: ios 

  tasks:
    - name: GATHER ROUTER FACTS
      ios_facts:
      register: show_output

    - debug:
        var: show_output
