---
- name: GATHER INFORMATION FROM ROUTERS
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: GATHER ROUTER FACTS
      ios_facts:
      register: show_output

    - debug:
        msg: "{{ show_output }}"