# This playbook uses to gather all the facts related to routers
---
- name: GATHER INFORMATION FROM ROUTERS
  hosts: all  # Executes the playbook across the all the hosts under the SmartInventory
  connection: network_cli # Informs to use the network connections for the router
  gather_facts: no 

  tasks:
    - name: GATHER ROUTER FACTS
      ios_facts: # Module to collect facts from the router.
      register: show_output

    - debug:
        msg: "{{ show_output }}"